### ISSUE TITLE
Adding a de-anonymize function

### ISSUE THREAD

**Issue by TheWall89** [keiichishima/yacryptopan#3]
Hi keiichishima,
thanks for merging my previous pull request and for adding me to contributors.

I have a feature proposal for yacryptopan: it would be difficult to write a _de-anonymization_ function? In my use-case I need to anonymize some network traces so that many people can experiment with them, but I would like to easily obtain de-anonymized addresses when I need to.

Because cryptopan is based on AES I think this should be theoretically feasible, but I don't know how to do it or how much time it would take. What do you think about it?

**Comment by keiichishima** [comment]
Deanonymizing is not possible.  It's one-way conversion.  The only way to recover the anonymized addresses to its original one is to calculate the entire address space and make a map beforehand.

**Comment by TheWall89** [comment]
Ah ok. In fact that's the solution I'm adopting right now in my code.

Thank you very much for the answer. Best regards :)
